name: Purge jsDelivr cache

on:
  push:
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/GiulianoReinhart/custom-bga@main/custom.css"
